version: 2

models:
  - name: fact_transactions_daily
    description: >
      Daily aggregated interbank transactions by originating bank and currency.
      This fact table provides transaction volume and monetary metrics for
      analytical and reporting purposes.
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - transaction_date
            - bank_code
            - currency_code
      - dbt_utils.expression_is_true:
          expression: "total_amount_paid >= 0"



    columns:
      - name: transaction_date
        data_type: date
        description: "Date on which the transactions occurred."
        tests:
          - not_null

      - name: bank_code
        data_type: string
        description: "Code of the originating bank."
        tests:
          - not_null
          - relationships:
              to: ref('dim_bank')
              field: bank_code

      - name: currency_code
        data_type: string
        description: "Currency used for the transaction."
        tests:
          - not_null
          - relationships:
              to: ref('dim_currency')
              field: currency_code

      - name: total_transactions
        data_type: int64
        description: "Total number of transactions for the given day, bank, and currency."
        tests:
          - not_null

      - name: total_amount_paid
        data_type: float64
        description: "Total monetary value of transactions for the given day, bank, and currency."
        tests:
          - not_null
          
  - name: rpt_bank_daily_volume
    description: >
      Daily transaction volume aggregated by originating bank.
      This report-level table is designed for analytical consumption
      and dashboard visualization.

    columns:
      - name: transaction_date
        description: "Date of the transaction activity."
        tests:
          - not_null

      - name: bank_code
        description: "Code of the originating bank."
        tests:
          - not_null
          - relationships:
              to: ref('dim_bank')
              field: bank_code

      - name: daily_volume
        description: "Total monetary value of transactions per bank per day."
        tests:
          - not_null

  - name: rpt_hourly_volume
    description: "Hourly transaction volume aggregation for heatmap visualization"
    columns:
      - name: transaction_date
        tests:
          - not_null
      - name: transaction_hour
        tests:
          - not_null

  - name: rpt_currency_flow
    description: "Currency exchange flow analysis between payment and receiving currencies"
    columns: 
      - name: source_currency
        tests:
          - not_null
      - name: target_currency
        tests:
          - not_null

  - name: rpt_bank_flow_matrix
    description:  "Bank-to-bank transaction flow matrix for network analysis"
    columns:
      - name: from_bank
        tests:
          - not_null
      - name: to_bank
        tests:
          - not_null

  - name: rpt_risk_summary
    description: "Risk and anomaly detection summary with flagged transaction rates"
    columns:
      - name: transaction_date
        tests:
          - not_null
      - name: flag_rate_pct
        description: "Percentage of transactions flagged as suspicious"

  - name: rpt_pipeline_health
    description: "Pipeline health monitoring metrics for operational dashboards"
    columns:
      - name: transaction_date
        tests:
          - not_null
          - unique